sudo: false
branches:
    only:
        - master
        - stable
language: python
python:
    - '2.7'
addons:
  apt:
    packages:
      - python-scipy
      - libatlas3gf-base
      - libatlas-dev
      - liblapack-dev
      - libopenblas-dev
install:
    - pip install -r requirements.txt
    - pip install --upgrade --force-reinstall pytest>=3
script:
    - python -m pytest -v --color=yes
os:
  - linux
  - osx