name: rltk_env
dependencies:
- cython=0.25.2=py27_0
- ipython=5.3.0=py27_0
- ipython-notebook=4.0.4=py27_0
- jinja2=2.7.3=py27_1
- jsonschema=2.4.0=py27_0
- libsodium=0.4.5=0
- libxml2=2.9.2=0
- libxslt=1.1.28=0
- lxml=3.6.4=py27_0
- openssl=1.0.2h=1
- pip=9.0.1=py27_0
- ptyprocess=0.4=py27_0
- pycosat=0.6.1=py27_0
- pygments=2.0.2=py27_0
- pytest=3.0.5=py27_0
- python=2.7.12=1
- pyyaml=3.11=py27_0
- pyzmq=14.6.0=py27_0
- tornado=4.1=py27_0
- wheel=0.29.0=py27_0
- yaml=0.1.4=0
- zeromq=4.0.5=0
- zlib=1.2.8=3
- nb_conda=2.0.0=py27_0
- pip:
  - alabaster>=0.7.9
  - digCrfTokenizer
  - jsonpath-rw>=1.4.0
  - jupyter>=1.0.0
  - munkres==1.0.8
  - nbsphinx>=0.2.13
  - numpy>=1.12.0
  - Sphinx>=1.5
  - scikit-learn>=0.18.1
  - scipy>=0.19.0
  - sphinx-autobuild>=0.6.0
  - sphinxcontrib-napoleon>=0.6.0